name: Build Jekyll and push to "rendered"

# based on https://gist.github.com/elstudio/38bacfe7aab63da082a418fd3a1ddb66

on:
  push:
    branches:
      - jekyll

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Jekyll Picture Tag requires libvips libraries for resizing images, which must be installed
    #   - name: Install JPT's dependencies
    #     run: sudo apt-get install libvips-tools
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2147483647
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Run Jekyll
        run: bundle exec jekyll build
      - name: Publish to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: rendered
          FOLDER: _site
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}  
